### ISSUE TITLE
cannot recognize local module and need clear requirements.txt generation option

### ISSUE THREAD

**Issue by liesauer** [damnever/pigar#65]
so there are two problem:
1. `pigar` cannot recognize my local module
![image](https://user-images.githubusercontent.com/8676741/71810564-a392be00-30ad-11ea-8c21-bc398fff1a04.png)
![image](https://user-images.githubusercontent.com/8676741/71810579-ab526280-30ad-11ea-849b-8b79a7f217f7.png)

2. `requirements.txt` is too verbose, i believe this feature is from #6 , but it will be great if has a option to control this behavior, such as `--detailed` or something, if i import tons of modules, `requirements.txt` will be pretty huge, the most important thing is git will record the changes if my codes do some changes(that is because `requirements.txt` has those references line numbers), so i need to commit `requirements.txt` frequently
![image](https://user-images.githubusercontent.com/8676741/71810641-c8873100-30ad-11ea-9c98-2d16b50c7a4c.png)

**Comment by bganglia** [comment]
1.
@liesauer I have noticed the first quirk as well.

The code does check whether the imported modules are local files, but if a package with the same name is available on PyPI, it assumes that the user wanted that one. 

See the lines of code below, which execute if you enter "y". (Variables: db = connection to PyPI database, name = package name). If the package is in PyPI, the module is moved from self._maybe_local_mods to in_pypi.

```
                        rows = db.query_all(name)
                        pkgs = [row.package for row in rows]
                        if pkgs:
                            in_pypi.add(name)
                            if name in self._maybe_local_mods:
                                self._maybe_local_mods.remove(name)
                        for pkg in self._best_matchs(name, pkgs):
                            latest = check_latest_version(pkg)
                            reqs.add(pkg, latest, detail.comments)
```

It might be good to assume the user wanted the local module instead, since (at least within the directory) the local module will be imported first anyway. 

On the other hand, downloading the package anyway may be a feature. @damnever, what do you think?

2.
@damnever I can work on adding this option to control the requirements.txt verbosity.

**Comment by liesauer** [comment]
> It might be good to assume the user wanted the local module instead, since (at least within the directory) the local module will be imported first anyway.

i agree with this, but i think implement a import resolver that searches each path of `PYTHONPATH` would be better, if a module insides `lib` or `site-packages`, we can consider that is a built-in module or a `PyPI ` module. and if a local module is found first, then no `PyPI` checking, but this depends on the order in `PYTHONPATH`.

**Comment by damnever** [comment]
@liesauer, an option to control the reference comments is reasonable. @bganglia I am glad that you can work on this 👍

pigar searches modules remotely only if modules are not installed locally, except in this case, that is why `demjson` and the others are not on the `not found yet` list.

**Comment by damnever** [comment]
> It might be good to assume the user wanted the local module instead, since (at least within the directory) the local module will be imported first anyway.

I agree with this too.
